name: Delete Environment on Branch Deletion

on:
  delete:

jobs:
  deleteEnvironment:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'branch'
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Requests
        run: pip install requests

      - name: Delete GitHub Environment
        run: |
          import requests
          import os

          branch_name = '${{ github.event.ref }}'.replace("/", "%2F")
          environment_name = branch_name
          headers = {
            'Authorization': f'Bearer ${{ secrets.TOKEN }}',
            'Accept': 'application/vnd.github+json',
            'X-GitHub-Api-Version': '2022-11-28',
          }

          url = f'https://api.github.com/repos/${{ github.repository }}/environments/{environment_name}'
          response = requests.delete(url, headers=headers)

          if response.status_code == 204:
              print(f"Environment {environment_name} deleted successfully.")
          else:
              print(f"Failed to delete environment {environment_name}. Status code: {response.status_code}")
              exit 1
        shell: python
