name: Gitpod Workspace on New Branch

on:
  pull_request:
    branches:
      - "dev/**"

jobs:
  gitpod-workspace-creation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Gitpod CLI
        run: |
          wget -O gitpod https://gitpod.io/static/bin/gitpod-cli-linux-amd64
          chmod +x gitpod
          ./gitpod login --token ${{ secrets.GITPOD_TOKEN }} --org ${{ secrets.GITPOD_ORG }}

      - name: Create a Gitpod workspace for the new branch
        id: create_workspace
        run: |
          branchName=${GITHUB_REF#refs/heads/}
          repoFullName=${{ github.repository }}
          WORKSPACE_URL=$(./gitpod ws create github.com/$repoFullName/tree/$branchName --dont-wait)
          echo "BRANCH_NAME=$branchName" >> $GITHUB_ENV
          echo "WORKSPACE_URL=$WORKSPACE_URL" >> $GITHUB_ENV

      - name: Stop the workspace
        id: stop_workspace
        if: steps.create_workspace.outputs.exit_code == 0
        run: |
          sleep 60
          ./gitpod ws stop ${{ env.WORKSPACE_URL }}

    environment:
      name: ${{ GITHUB.ref_name }}
      url: https://gitpod.io/start/#${{ env.WORKSPACE_URL }}
